"""Add User.trello_username

Revision ID: 3800cbc28f7e
Revises: 750a3c3352a0
Create Date: 2020-06-14 09:02:43.483476

"""
from alembic import op
import sqlalchemy as sa
from app.models import User
import os
from syncboom import perform_request


# revision identifiers, used by Alembic.
revision = '3800cbc28f7e'
down_revision = '750a3c3352a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('trello_username', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###
    # Populate trello_username for all existing users
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    users = session.query(User)
    num_users = len(list(users))
    if num_users > 0:
        print("Populating trello_username for all %d users" % num_users)
        for u in users:
            if u.trello_token:
                # Determine that Trello user's username
                trello_details = perform_request("GET", "members/me",
                    key=os.environ.get('TRELLO_API_KEY'),
                    token=u.trello_token)
                u.trello_username=trello_details["username"]
                print("Trello username for %s (id %d): %s" %
                    (u, u.id, u.trello_username))
            else:
                print("%s (id %d) has no Trello token" % (u, u.id))
    session.commit()


def downgrade():
    # Deleting a column in SQLite has us go through Batch mode instead of:
    # op.drop_column('user', 'trello_username')
    with op.batch_alter_table("user") as batch_op:
        batch_op.drop_column('trello_username')
