"""Task start and end times, and outcomes

Revision ID: 750a3c3352a0
Revises: 9d787c01a5cd
Create Date: 2020-05-25 14:03:57.238014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750a3c3352a0'
down_revision = '9d787c01a5cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('timestamp_start', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('timestamp_end', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('status', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_task_timestamp_start'), 'task', ['timestamp_start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_timestamp_start'), table_name='task')
    op.drop_column('task', 'status')
    op.drop_column('task', 'timestamp_end')
    op.drop_column('task', 'timestamp_start')
    # ### end Alembic commands ###
