"""Add Mapping table

Revision ID: 9d787c01a5cd
Revises: a64a5caece00
Create Date: 2020-05-21 10:04:29.708057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d787c01a5cd'
down_revision = 'a64a5caece00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.Column('master_board', sa.String(length=128), nullable=True),
    sa.Column('destination_lists', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_name'), 'mapping', ['name'], unique=False)
    op.create_table('mappings',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mapping_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mapping_id'], ['mapping.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mappings')
    op.drop_index(op.f('ix_mapping_name'), table_name='mapping')
    op.drop_table('mapping')
    # ### end Alembic commands ###
